apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc-app
spec:
  selector:
    {{- toYaml .Values.backstage.labels | nindent 4 }}
  ports:
    {{- toYaml .Values.backstage.svc.ports | nindent 4 }}
