apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: '/mnt/data'
